Algoritmo "MENOR DE TRÍS"

Var
   a,b,c:inteiro



Inicio
   escreval("INFORME OS VALORES")
   escreva("A:")
   Leia(a)
   escreva("B:")
   Leia(b)
   escreva("C:")
   Leia(c)

   se(a < b) e (a < c )ent„o
      escreval("o menor numero È :",a)
   senao
      se(b < a) e (b < c)ent„o
         escreval("o menor numero È :",b)
      senao
         escreval("o menor numero È :",c)
      fimse


   fimse



Fimalgoritmo