Algoritmo "tabuada"

Var
n:inteiro
resp:caractere


Inicio
repita
escreval("Deseja a tabuada para qual valor?")
leia(n)
escreval(n," x 1 =",n*1)
escreval(n," x 2 =",n*2)
escreval(n," x 3 =",n*3)
escreval(n," x 4 =",n*4)
escreval(n," x 5 =",n*5)
escreval(n," x 6 =",n*6)
escreval(n," x 7 =",n*7)
escreval(n," x 8 =",n*8)
escreval(n," x 9 =",n*9)
escreval(n," x 10 =",n*10)

escreval("deseja consultar outro numero? s/n")
leia(resp)

ate (resp ="n")

Fimalgoritmo